# Syntax
hier gehen wir grad durch die Basic TF-Befehle

Wir können im Falle wenn TF2 ausgerollt ist auch die Befehle aus TF1 wieder zurückladen. dazu geben wir folgenden Befehl ein:
> import tensorflow.compat.v1 as tf tf.disable_v2_behavior()

In [1]:
import tensorflow as tf

C:\Users\1810837475\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\1810837475\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\1810837475\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\1810837475\.conda\envs\tensorfl

In [2]:
# Version # Achtung der Kurs von Udemy ist in 1.6.0 => kann änderungen in der Syntax geben
# aktuell is TF 2. X akutell => oben habe ich den Überrsetzungsbefehl
# Achtung TF ist brutal zickig was cpu / GPU version bedingt
print(tf.__version__)
!python --version

1.14.0
Python 3.7.7


TF ist leider Gottes unfassbar Syntax zickig. Da hierbei jedoch auch die Releases immer eine große Syntaxänderung mitbringen, ist dies halt leider etwas Komplex. 

# Tensoren
Auf Tensoren kann man operatoren angeben
Tensor = Cooles Wort für ein n-Dimnesionalles Array
## Tensoren BSP1
hier werden in den Tensor Strings abgelget

In [3]:
# Tensor anlegen
hello = tf.constant('Hello')

In [4]:
print(type(hello))

<class 'tensorflow.python.framework.ops.Tensor'>


In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
# Tensor anlegen
world = tf.constant('World')

In [7]:
# Operation
result = hello + world
result # <= das ist ein Objetkt. um das auszufügren muss eine Session erzeugt werden

<tf.Tensor 'add:0' shape=() dtype=string>

**Good to Know**<br>
TF-Objekte werden immer in Sessions ausgeführt. Sprich ich beschreibe erst den Graphen, dann kann ich diesen erst ausfürhen. Für das Ausführen brauche ich wiederum eine Session. Siehe nächster Junk: 

In [8]:
with tf.Session() as sess:
    result = sess.run(hello+ world)

## Tensoren BSP2
hier werden int in den Tensoren abgelegt

In [9]:
a = tf.constant(10)
b = tf.constant(20)


In [10]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [11]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    result = sess.run(a+ b)
result

30

## Tensoren BSP3
hier werden Matrizen in den Tensoren abgelegt

In [13]:
const = tf.constant(10)

In [14]:
print(const) #<= hier gibt es den tensor zurück

Tensor("Const_4:0", shape=(), dtype=int32)


In [15]:
fill_mat = tf.fill((4,4),10)

In [16]:
myzero = tf.zeros((4,4))

In [17]:
myones = tf.ones((4,4))

In [18]:
myrand = tf.random_normal((4,4), mean = 0, stddev =0.5)

In [19]:
myrandu = tf.random_uniform((4,4), minval=0, maxval = 1)

In [20]:
my_ops =[const, fill_mat, myzero, myones, myrand, myrandu]

In [21]:
# dieser Befehl geht nur in der Sesstion
sess = tf.InteractiveSession()

In [22]:
for op in my_ops:
    print(sess.run(op))
    print()

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 0.18339723 -0.21873115  0.30109465  1.232304  ]
 [ 0.5745965   0.28448397  0.19904809  0.06912379]
 [-0.8805558  -0.18788534  0.43886185  0.59962124]
 [ 0.3209257  -0.25052992 -0.6017481  -0.6210727 ]]

[[0.98021734 0.37101686 0.3317461  0.27598178]
 [0.87160397 0.6087352  0.7194922  0.1121068 ]
 [0.54575    0.82911205 0.7713833  0.34258127]
 [0.8273896  0.89525115 0.817708   0.633183  ]]



In [23]:
a = tf.constant([[1,2],[3,4]])

In [24]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [25]:
b = tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [26]:
# Matrizenmultiplikation

In [27]:
result = tf.matmul(a,b)

In [28]:
sess.run(result)

array([[210],
       [430]])


![Bsp MatrixMultiplikaiton](./imgs/Mat-Multi.png)

# Graphen
Graphen sind Gruppen von Verknüpfungen (eng: vertices = Scheitelpunkte) Diese Verknüpfungen heißen „edges“ In TensorFlow ist jede Verknüpfung eine **Operation** mit möglichen **Inputs** die einen **Output** liefert.

Graph = die gesammte untere Grafik:

Bsp-Graph den wir erstellen
![Bsp MatrixMultiplikaiton](./imgs/graphtf1.png)

Ganz grob in eigeninterpreation:<br>
Ein Knoten ist ein Tensor, und die Operationen sind die Kanten

In [29]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [30]:
# TF-Objekte werden immer in Sessiosn ausgeführt
with tf.Session() as sess:
    result = sess.run(n3)
result

3

In [31]:
n3

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [32]:
print(tf.get_default_graph())

Hier erstelle ich einen anderne Graphen

In [33]:
g = tf.Graph()

In [34]:
g

In [35]:
g1 = tf.get_default_graph()
g2 = tf.Graph() # hier fügen wir einen zweiten Graphen hinzu

In [36]:
g1 is tf.get_default_graph()

True

In [37]:
g2 is tf.get_default_graph()

False

In [38]:
g1 # Hier ist die ID = 0x28d70d43e88

In [39]:
g2

In [40]:
# einen anderen Graphen als standardgraph setzen
# dieser Junk setzt g2 nur in dieser Session als Default-Graph
with g2.as_default():
    print(g2 is tf.get_default_graph())

True


In [41]:
g2 is tf.get_default_graph()

False

# Variablen & Platzhalter

**Variablen**

* TensorFlow verfeinert die Parameter des Modells während der Optimierungsphase des Prozesses

* Variablen können während der gesamten Sitzung die Werte von Gewichten (weigths) und Neigungen (biases) erhalten.

* Variablen müssen initialisiert werden

**Platzhalter**
* Platzhalter sind zu Beginn leer und werden dann dazu verwendet mit konkreten Trainingsdaten befüllt zu werden
* Platzhalter benötigen jedoch einen erwarteten, deklarierten Datentypen (tf.float32) mit einem optionalen „shape“ Argument.

# BSP Implementierung in TF

In [42]:
# import tensorflow as tf
sess = tf.InteractiveSession()

C:\Users\1810837475\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\client\session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [43]:
my_t = tf.random_uniform((4,4),0,1) # <= erstellen des Tensor-Objektes

In [44]:
my_Var = tf.Variable(initial_value=my_t) # <= umwandlung von Tensor in Variable
my_Var

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>

In [45]:
# sess.run(my_Var) # <= fehler weil die Variable nicht initialisiert ist
init = tf.global_variables_initializer()
init.run()
sess.run(init)

In [46]:
sess.run(my_Var)

array([[0.51983774, 0.50739694, 0.3902092 , 0.165851  ],
       [0.11574948, 0.7653692 , 0.7680583 , 0.32400942],
       [0.47475386, 0.29064882, 0.23699832, 0.10185897],
       [0.8210697 , 0.91471434, 0.8404311 , 0.82223797]], dtype=float32)

**Placeholder**
Mit den Placeholder kann man resourcen schon vorab zuweisen

In [47]:
# Placeholder anlgen für float
ph = tf.placeholder(tf.float64)

# Placeholder anlgen für int / ganzzahl
ph = tf.placeholder(tf.int32)

# Placeholder anlgen für int / ganzzahl // mit shape = Input daten
ph = tf.placeholder(tf.int32, shape=(4,5))
# hier gebe ich 5 feature mit, weis aber eben nicht wieviel Instanzen /
ph = tf.placeholder(tf.int32, shape=(None,5))