# Numpy
https://towardsdatascience.com/lets-talk-about-numpy-for-datascience-beginners-b8088722309f

In [5]:
import numpy as np

In [6]:
# Create vector von List
my_list = [1, 2, 3, 4, 5]
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [9]:
# Create Matrix von mehrdimensionaler Liste
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [16]:
# Sequenzen
my_list = np.arange(10)#ORmy_list = np.arange(0,10)
print(my_list)
my_list = np.arange(0,11,2)
print(my_list)
my_zeros = np.zeros(7)
print(my_zeros)
my_ones = np.ones(5)
print(my_ones)


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [20]:
# Sequenzen in Matritzen
two_d = np.zeros((3,5))
print(two_d)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.        ]


In [ ]:
# linspace macht dass exakt die Aufteilung dazwischen stattfindet
lin_arr = np.linspace(1, 3, 15)
print()
print(lin_arr)

In [22]:
# Matrix
my_matrx = np.eye(6)    
print(my_matrx)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [23]:
# matrix mit 5 spalten & 3 Zeilen
np.random.randn(3,5)

array([[-0.1890858 , -0.05831819, -0.58525977,  1.04583075,  0.46938555],
       [ 1.47847426, -0.32743414, -2.2377986 ,  0.037953  ,  0.66445085],
       [ 0.09753164, -0.58475725, -2.22457776, -1.30782787,  0.09823543]])

In [25]:
# converting 1d in 2d 
arr = np.random.rand(25)
print(arr)
arr.reshape(5,5)
print()
print(arr)


[0.44529488 0.12028035 0.56737235 0.24441402 0.24664845 0.11442185
 0.36610129 0.21887851 0.52418328 0.42369592 0.40108522 0.79747753
 0.21060816 0.22255648 0.98669029 0.35811407 0.10707313 0.5468217
 0.70217085 0.20884735 0.57949985 0.58456655 0.70022566 0.85126028
 0.40749741]

[0.44529488 0.12028035 0.56737235 0.24441402 0.24664845 0.11442185
 0.36610129 0.21887851 0.52418328 0.42369592 0.40108522 0.79747753
 0.21060816 0.22255648 0.98669029 0.35811407 0.10707313 0.5468217
 0.70217085 0.20884735 0.57949985 0.58456655 0.70022566 0.85126028
 0.40749741]


In [33]:
## max min in einem Vektor absolut
arr_2 = np.random.randint(0, 20, 10)
print(arr_2)
arr_2.max() #This gives the highest value in the array arr_2.min() #This gives the lowest value in the array
arr_2.min()
# hier die indexe dazu
print(arr_2.argmax()) #This shows the index of the highest value in the array 
print(arr_2.argmin()) #This shows the index of the lowest value in the array

[18 19 12  5  6  8 11 18  6  9]
1
3


In [35]:
# shape of an array
arr.shape

(25,)

In [43]:
my_array = np.arange(0,11)
print(my_array)
my_array[8]  #This gives us the value of element at index 8
my_array[2:6] #This returns everything from index 2 to 6(exclusive)
my_array[:6] #This returns everything from index 0 to 6(exclusive)
my_array[5:] #This returns everything from index 5 to the end of the array.

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 5,  6,  7,  8,  9, 10])